### ISSUE TITLE
Lnd Hotfix Required

### ISSUE THREAD

**Issue by dolcalmi** [hsjoberg/blixt-wallet#1051]
Creating the issue because not sure how is the procedure to update lnd

Emergency hot fix: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.4-beta

**Comment by hsjoberg** [comment]
We're working on getting a hotfix out.

**Comment by hsjoberg** [comment]
Fixed in https://github.com/hsjoberg/blixt-wallet/releases/tag/v0.6.0
