### ISSUE TITLE
[Feature  request] Change bitcoin node before restore process

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#1053]
### Description
Right now we have the option to add Tor option before starting the restore process, to help connecting with Tor only peers.
We notice that some users, do not have very good Tor connection so that process could fail from the start and create a lot of confusion for newbies.
Being able to add a local bitcoin node or a clearnet one could help the recovery process or at least the initial sync to go well.

### Solution proposal
**Option A**
In the start screen, when the user have to add the seed + SCB file, add an alert text popup or something to inform the user that can go to top right drawer and activate Tor and change the bitcoin node sync if thinks that his Tor or internet connection do not allow him to connect to default bitcoin node.

**Option B**
In the start screen, even if the user didn't know about that top menu, or forgot to add Tor, make a popup alert, when he press the recovery button that says: "Did you try to recover old node channels that were open with Tor only peers? Go to top menu and activate it please."
If the neutrino sync connection it detects failed connection with default node, stop the process and popup the user with a message where should input a new bitcoin node to connect.
Also this popup can be used in general not just in restoring process. Many users do not realize why their Blixt node is not syncing and don't mind to change that bitcoin node.

**Comment by Darth-Coin** [comment]
Added to v0.6.1

**Comment by hsjoberg** [comment]
It was added already in v0.6.0
