### ISSUE TITLE
Add language in first start screen

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#1073]
## Description
In the top right menu, where are the "activate Tor" and "set bitcoin node", now that we have so many cool languages, will be good to offer the user the right experience: Add the "choose your language" option.

In this way user will start from the beginning using Blixt with the language that is comfortable.

**Comment by hsjoberg** [comment]
See how `HelperWindows/SelectList` works in Settings.tsx
You will have to add a screen with this component to the Welcome screens navigator.

You might as well remove the Android-specific code that uses a modal instead of going to a screen. That makes the code cleaner.
