### ISSUE TITLE
[Feature request] Opening channel with all available balance

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#1077]
### Proposal
Add option to use all available balance when opening a new channel.

### Description
Right now in the screen of opening a new channel we have the following: Node URI,  Amount sat,  Amount fiat, Fee rate, display available balance in sats.
User cannot use for example all sats from a left UTXO or want to use all sats available. Will always remain with some dust sats lost in some UTXOs.
User have to first set a fee, calculate manually how much in total that fee will be. A noob user will NOT do that!
For example how do to use all sats:
- I put a low fee, 3sat/vB.
- I put all sats available in the "amount sat" field
- click open channel

Yes, will give me an error, but is displaying exactly the difference calculated for fee... 333 sats for example.
So I go to "amount sat" and deduct the total fee 333 sats and the hit open channel.
Done, it worked. But these are several steps user will have to do.

### Solution
Add a button next to "amount sat" that says "use all balance".
That will deduct automatically the total fee from available balance.
I will move the fee rate under the node URI, so user will be pushed to put first the fee. That is necessary in order to be able to calculate the exact amount of fee deducted from the "amount sat" opening channel.
Or if this is not possible due to LND code limitations...
At least show how much is total fee in sats, when user put manually the fee rate. In this way it can be manually deducted from total available and put the amount that can be really used, leaving empty the onchain balance.

![image](https://user-images.githubusercontent.com/56997124/203539830-c5a57062-8d20-48d4-a982-5ca70ebc8c18.png)

**Comment by hsjoberg** [comment]
Fixed in 399b23bab3fca4d7e7a7feb28cc57aa205882d8b
