### ISSUE TITLE
Undefined is not a function in LndMobile help center.

### ISSUE THREAD

**Issue by niteshbalusu11** [hsjoberg/blixt-wallet#1094]
`init` and `sigkill LND mobile service` returns undefined is not a function. 

![image](https://user-images.githubusercontent.com/84944042/206918271-3f19f74c-92c2-491e-89e9-af2acdd6d7ee.jpeg)

**Comment by hsjoberg** [comment]
Fixed in 52bef7a02c12865e4a91734efd37c0767e5bc2ee. Thank you!
