### ISSUE TITLE
Small correction in Settings UI

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#1141]
### Just a reminder
Please move the position of "Enable Dunder LSP" option in Settings, from "Experiment" section to "Lightning Network" section, next to "Set Dunder LSP Server".
In this way is much easier for the user to manage his Dunder settings.

![image](https://user-images.githubusercontent.com/56997124/225859910-879adad1-68cb-4efd-8524-fa65f4515f25.png)

**Comment by hsjoberg** [comment]
Fixed in a31305ff98966858d96d57ea75d2724391e4d4e6.
