### ISSUE TITLE
On-boarding: Skip waiting for syncedToChain to be true

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#116]
It needs to be evaluated if this is a good idea -- waiting for chainsync takes quite a lot of time and it can be a very bad experience for new users to lock them to the "Syncing chain"-screen.

The issue though is that the user cannot AFAICT send nor receive payments before the chain is fully synced, but it might be better to let the user in anyways, so they can get familiar with the app.

Apps like Pheonix let the user in immediately, I'm still not sure how they accomplish the syncing problem. They are probably "cheating" in some way.

**Comment by sesam** [comment]
+1 on letting user in. But maybe this already happens?

Phoenix probably lets the user use already existing channels on start, sacrificing Phoenix team-owned liquidity to get things rolling. Should tie in with something in their features list or release notes.

**Comment by hsjoberg** [comment]
Thanks for the feedback @sesam, I'll work in implementing this.

> But maybe this already happens?

No, the `lastSync` variable would be set to 0, which will force the user to wait.
In normal circumstances, this is fine because it won't take long time at all (e.g 2000 blocks behind goes quick) but for the first time opening the app, it would take quite a long time.

https://github.com/hsjoberg/blixt-wallet/blob/0afb6c2ef9f896ccafa806d223ebb27658d13736/src/state/Lightning.ts#L67-L78

> Phoenix probably lets the user use already existing channels on start, sacrificing Phoenix team-owned liquidity to get things rolling.

Right, I need to read up on how Pheonix does things. :sweat_smile:

**Comment by hsjoberg** [comment]
(I'm also thinking about embedding an up-to-date blockchain in the actual apk installation file and move that to the appropriate lnd-folder first time the app starts up, thus dramatically minimizing startup time, but hardcore Bitcoiners would be against this for obvious trust-based reasons. :sweat_smile:)

**Comment by hsjoberg** [comment]
Fixed in 116f988a911a24c104d964ad86ddaa06ff35006b

**Comment by hsjoberg** [comment]
Implemented in e0f2e4dfa0852b7f768637be972e7903a58d2a8d
