### ISSUE TITLE
[Feature request] Add option to compact db

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#1191]
I notice that in the last week the data used in Blixt increased from 1.2 GB to 2.01 GB
Please consider adding an option, where user could activate it and restart Blixt node in "compaction mode".
Add an alert on the screen that could take some time.
After the compaction is done, make it automatically disabled, so next time when user start Blixt will not doing again compaction. To be only one time, by request.

![image](https://user-images.githubusercontent.com/56997124/236860755-acd18e89-8109-4e11-ae01-e50f88e789fd.png)

**Comment by hsjoberg** [comment]
Implemented in c03a9dd
