### ISSUE TITLE
Improve hodl invoice support

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#1205]
Related to #432

**Comment by djkazic** [comment]
This should bundle a fix to the `addTransaction` and `updateTransaction` actions to fix a data race. See commit here for details on the implementation: https://github.com/djkazic/blixt-wallet/commit/fa4cdd088e7f629dca54b4a9a1005609f996cd31

**Comment by hsjoberg** [comment]
Fixed in 7b1b49c58fc351a533ffe3551b054a9ee4b4334f
