### ISSUE TITLE
Fix foregound service type 

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#1293]
In Android 14, foreground services must explain the intent of the service.

https://developer.android.com/about/versions/14/changes/fgs-types-required

This will hopefully make phone vendors respect AOSP foreground service policies, which has been a [huge problem](https://dontkillmyapp.com) in the past.
Samsung for example is promising to follow it: https://developer.samsung.com/mobile/app-management.html

None of the service types appear to be a reasonable choice for our Lnd service, so perhaps we should use [`specialUse`](https://developer.android.com/about/versions/14/changes/fgs-types-required#special-use) and explain via metadata that our intent is to run Lightning network node persistently for the user, in order to receive incoming payments, et cetera.

**Comment by djkazic** [comment]
I think abusing mediaplay might work as a fallback

**Comment by hsjoberg** [comment]
> I think abusing mediaplay might work as a fallback

I'm afraid they will punish us if we aren't honest.*

Right now I'm leaning towards using `specialUse`. I found out that you're supposed to [declare your service](https://support.google.com/googleplay/android-developer/answer/13392821) in the Play Console, which gives us an opportunity to clearly explain what we want to do.


*) I suppose we could introduce podcasting support as Breez does lol.
Or make Blixt into a music player playing music from John Berg and Dj Kazic.
