### ISSUE TITLE
Stuck crashing on 0.6.9

### ISSUE THREAD

**Issue by mattixtech** [hsjoberg/blixt-wallet#1369]
Recently I upgraded to version 0.6.9. It was working fine at first but is now crashing immediately every time I open the app.

I changed the option to enable persistent mode and also triggered a chain sync before closing the app. Next time I opened the app it immediately crashed and does so every time I open it. Sometimes I briefly see "Initializing Tor" before it crashes.

Is there anything I can do to troubleshoot this? I currently have one lightning channel open that I would prefer not to close. There is also an on-chain balance if that makes a difference.

**Comment by hsjoberg** [comment]
Hi @mattixtech. Thank you for your bug report.
We are looking into the issue right now.

If you happen to use Telegram, you're welcome to join @BlixtWallet.

**Comment by hsjoberg** [comment]
Issue fixed im fed028b97d10fba263fd142a96feeec51db6600b. Thank you again for the bug report.

I will have a new release out very soon.

**Comment by mattixtech** [comment]
Awesome, thanks. Look forward to the new version.

**Comment by hsjoberg** [comment]
Hi again @mattixtech, I've published a new build that should fix this issue.
You can download the APK here: https://github.com/hsjoberg/blixt-wallet/releases/tag/v0.6.9-420

**Comment by mattixtech** [comment]
Hi @hsjoberg , I updated to the latest version and confirmed the issue is fixed. Thanks a lot!
