### ISSUE TITLE
Node stopped syncing and won't restart

### ISSUE THREAD

**Issue by unsettledroell404** [hsjoberg/blixt-wallet#1402]
My wallet stopped syncing at block 822735.  The progress stays at 0%.

I have followed all suggestions on the FAQ but that did not help (tried on 4G and WiFi, connected to default node, etc)

I force closed the app and cleared the cache too, also did not help.

My phone's disk was full for a while but I created ample space yesterday. Idk if that is related.

What gives? Here is the log;

21:12:18.880 [DBG] CRTR: Reporting pair failure to Mission Control: pair=0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb -> 03a01da97af71f7859cd1b2b6a70f221ecd49f6eabf0bf1e267bae9570b47232a6, amt=25018475 mSAT
21:12:18.880 [DBG] CRTR: Setting 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb->03a01da97af71f7859cd1b2b6a70f221ecd49f6eabf0bf1e267bae9570b47232a6 range to [0 mSAT-25018475 mSAT]
21:12:18.880 [DBG] CRTR: Reporting pair failure to Mission Control: pair=026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93 -> 02324b351af4ff9afd9cff43abd1b46a7621412313f3c97e486af3e9f9dabb1535, amt=25002050 mSAT
21:12:18.880 [DBG] CRTR: Setting 026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93->02324b351af4ff9afd9cff43abd1b46a7621412313f3c97e486af3e9f9dabb1535 range to [0 mSAT-25002050 mSAT]
21:12:18.880 [DBG] CRTR: Reporting pair success to Mission Control: pair=03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7 -> 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb, amt=25014552 mSAT
21:12:18.880 [DBG] CRTR: Setting 03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7->0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb range to [100111137 mSAT-0 mSAT]
21:12:18.880 [DBG] CRTR: Reporting pair success to Mission Control: pair=0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb -> 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6, amt=25007050 mSAT
21:12:18.880 [DBG] CRTR: Setting 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb->02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 range to [100081113 mSAT-0 mSAT]
21:12:18.880 [DBG] CRTR: Reporting pair success to Mission Control: pair=02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 -> 026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93, amt=25004550 mSAT
21:12:18.881 [DBG] CRTR: Setting 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6->026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93 range to [100071106 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair failure to Mission Control: pair=026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93 -> 02324b351af4ff9afd9cff43abd1b46a7621412313f3c97e486af3e9f9dabb1535, amt=25002050 mSAT
21:12:18.881 [DBG] CRTR: Setting 026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93->02324b351af4ff9afd9cff43abd1b46a7621412313f3c97e486af3e9f9dabb1535 range to [0 mSAT-25002050 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7 -> 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb, amt=25014552 mSAT
21:12:18.881 [DBG] CRTR: Setting 03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7->0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb range to [100111137 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb -> 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6, amt=25007050 mSAT
21:12:18.881 [DBG] CRTR: Setting 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb->02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 range to [100081113 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 -> 026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93, amt=25004550 mSAT
21:12:18.881 [DBG] CRTR: Setting 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6->026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93 range to [100071106 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb -> 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6, amt=25007050 mSAT
21:12:18.881 [DBG] CRTR: Setting 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb->02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 range to [100081113 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 -> 026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93, amt=25004550 mSAT
21:12:18.881 [DBG] CRTR: Setting 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6->026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93 range to [100071106 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair failure to Mission Control: pair=026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93 -> 02324b351af4ff9afd9cff43abd1b46a7621412313f3c97e486af3e9f9dabb1535, amt=25002050 mSAT
21:12:18.881 [DBG] CRTR: Setting 026db2cbf3d8ab4a4c01eed2df432d20cf0a13136402097574209d2595cb9e9d93->02324b351af4ff9afd9cff43abd1b46a7621412313f3c97e486af3e9f9dabb1535 range to [0 mSAT-25002050 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7 -> 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb, amt=25014552 mSAT
21:12:18.881 [DBG] CRTR: Setting 03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7->0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb range to [100111137 mSAT-0 mSAT]
21:12:18.881 [DBG] CRTR: Reporting pair success to Mission Control: pair=03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f -> 03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1, amt=25001025 mSAT
21:12:18.882 [DBG] CRTR: Setting 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f->03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1 range to [25001025 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1 -> 02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69, amt=25000000 mSAT
21:12:18.882 [DBG] CRTR: Setting 03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1->02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69 range to [25000000 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7 -> 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb, amt=25024506 mSAT
21:12:18.882 [DBG] CRTR: Setting 03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7->0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb range to [100111137 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb -> 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6, amt=25017001 mSAT
21:12:18.882 [DBG] CRTR: Setting 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb->02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 range to [100081113 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 -> 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f, amt=25014500 mSAT
21:12:18.882 [DBG] CRTR: Setting 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6->03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f range to [25014500 mSAT-25014501 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb -> 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6, amt=10008000 mSAT
21:12:18.882 [DBG] CRTR: Setting 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb->02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 range to [100081113 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6 -> 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f, amt=10007000 mSAT
21:12:18.882 [DBG] CRTR: Setting 02bba7cbb652242bc2550fbdcc04fbe267598636e6a67ca3d347d87ebaf00796a6->03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f range to [25014500 mSAT-25014501 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f -> 03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1, amt=10001010 mSAT
21:12:18.882 [DBG] CRTR: Setting 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f->03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1 range to [25001025 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1 -> 02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69, amt=10000000 mSAT
21:12:18.882 [DBG] CRTR: Setting 03f1395985d44b683743de49cec697ea762d1e3c9e709063e435cb3868d1d167f1->02f1a8c87607f415c8f22c00593002775941dea48869ce23096af27b0cfdcc0b69 range to [25000000 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Reporting pair success to Mission Control: pair=03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7 -> 0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb, amt=10011002 mSAT
21:12:18.882 [DBG] CRTR: Setting 03ae183856194a53db145b72d62b15863bd8cfa083ce4ce35922afac9f4bdb10d7->0230a5bca558e6741460c13dd34e636da28e52afd91cf93db87ed1b0392a7466eb range to [100111137 mSAT-0 mSAT]
21:12:18.882 [DBG] CRTR: Mission control state reconstruction finished: n=68, time=18.168923ms
21:12:18.882 [DBG] SRVR: Instantiating payment session source with config: AttemptCost=100 + 0.1%, MinRouteProbability=0.01
21:12:18.913 [DBG] SRVR: Sweeper batch window duration: 30s
21:12:18.946 [DBG] CHBU: Crafting backup for ChannelPoint(9a6194f4057acf59883feab974fed4515cabf1dc9bf461a515bcfb6de881b279:0)
21:12:18.946 [INF] LTND: Channel backup proxy channel notifier starting
21:12:18.946 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=1.000000, min_chan_size=20000, max_chan_size=16777215, private=true, min_confs=1, conf_target=3
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: SignRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: WalletKitRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: AutopilotRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: ChainRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: InvoicesRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: PeersRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: NeutrinoKitRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: RouterRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: WatchtowerRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: WatchtowerClientRPC
21:12:18.947 [DBG] LTND: Populating dependencies for sub RPC server: DevRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: AutopilotRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: NeutrinoKitRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: PeersRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: RouterRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: SignRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: WalletKitRPC
21:12:18.950 [DBG] RPCS: Starting sub RPC server: WatchtowerRPC
21:12:18.951 [DBG] RPCS: Starting sub RPC server: ChainRPC
21:12:18.951 [DBG] RPCS: Starting sub RPC server: DevRPC
21:12:18.951 [DBG] RPCS: Starting sub RPC server: InvoicesRPC
21:12:18.951 [DBG] RPCS: Starting sub RPC server: VersionRPC
21:12:18.951 [DBG] RPCS: Starting sub RPC server: WatchtowerClientRPC
21:12:18.951 [INF] LTND: We're not running within systemd or the service type is not 'notify'
21:12:18.951 [INF] LTND: Waiting for chain backend to finish sync, start_height=822753
21:12:18.951 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:18.994 [DBG] RPCS: [/lnrpc.Lightning/SubscribeInvoices] requested
21:12:18.994 [INF] INVC: New invoice subscription client: id=1
21:12:18.996 [DBG] RPCS: [/lnrpc.Lightning/NewAddress] requested
21:12:18.999 [DBG] RPCS: [/lnrpc.Lightning/WalletBalance] requested
21:12:19.000 [DBG] RPCS: [/lnrpc.Lightning/SubscribeChannelEvents] requested
21:12:19.006 [DBG] RPCS: [newaddress] account=default type=UNUSED_TAPROOT_PUBKEY addr=bc1p34fluxpg8peujxyv4z27239003ena9da4t683rn002tk7mgj5nsqwa86sm
21:12:19.061 [DBG] RPCS: [/lnrpc.Lightning/ChannelAcceptor] requested
21:12:19.063 [DBG] RPCS: [/lnrpc.Lightning/SubscribeCustomMessages] requested
21:12:19.064 [DBG] RPCS: [/lnrpc.Lightning/GetRecoveryInfo] requested
21:12:19.064 [DBG] RPCS: [getrecoveryinfo] is recovery mode=false, progress=0
21:12:19.068 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:19.080 [DBG] RPCS: [/lnrpc.Lightning/ChannelBalance] requested
21:12:19.081 [DBG] RPCS: [channelbalance] local_balance=289989258 mSAT remote_balance=119206742 mSAT unsettled_local_balance=0 mSAT unsettled_remote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
21:12:19.083 [DBG] RPCS: [/lnrpc.Lightning/ListChannels] requested
21:12:19.083 [DBG] RPCS: [listchannels] fetched 1 channels from DB
21:12:19.161 [DBG] RPCS: [/lnrpc.Lightning/PendingChannels] requested
21:12:19.168 [DBG] RPCS: [/lnrpc.Lightning/GetNodeInfo] requested
21:12:19.568 [DBG] RPCS: [walletbalance] Total balance=0 BTC (confirmed=0 BTC, unconfirmed=0 BTC)
21:12:19.578 [DBG] RPCS: [/lnrpc.Lightning/SubscribeTransactions] requested
21:12:19.579 [INF] RPCS: New transaction subscription
21:12:19.952 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:20.141 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested

21:12:20.953 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:21.172 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:21.954 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:22.200 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:22.954 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:23.225 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:23.955 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:24.274 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:24.957 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:25.305 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:25.958 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:26.348 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:26.959 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:27.401 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:27.960 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:28.450 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:28.961 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:29.502 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:12:29.962 [DBG] LTND: Syncing to block timestamp: 2023-12-24 16:52:56 +0000 UTC, is synced=false
21:12:30.552 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested

**Comment by unsettledroell404** [comment]
I hit 'stop LND and delete neutrino files' and now it is stuck at blockheight 0, spamming this message in the log:

21:24:38.939 [DBG] RPCS: [/lnrpc.Lightning/GetInfo] requested
21:24:39.094 [DBG] LTND: Syncing to block timestamp: 2009-01-03 18:15:05 +0000 UTC, is synced=false

**Comment by unsettledroell404** [comment]
Changing the Bitcoin server to: bb1.breez.technology
Solved this.

Is this an issue with the app or the server?

For me it is solved but if this is an app issue maybe this needs to be checked.

**Comment by niteshbalusu11** [comment]
> Changing the Bitcoin server to: bb1.breez.technology Solved this.
> 
> Is this an issue with the app or the server?
> 
> For me it is solved but if this is an app issue maybe this needs to be checked.

we have been having some neutrino issues lately, working on fixes.

**Comment by hsjoberg** [comment]
Closing this as it has been fixed in #1403.
