### ISSUE TITLE
Infinity% during sync

### ISSUE THREAD

**Issue by rex4539** [hsjoberg/blixt-wallet#1408]
![IMG_3026](https://github.com/hsjoberg/blixt-wallet/assets/227442/4bcc17a8-7326-4b07-b3fe-37d9d0f413e0)

**Comment by rex4539** [comment]
Gets funnier.

![IMG_3027](https://github.com/hsjoberg/blixt-wallet/assets/227442/9393ceaf-f67a-4796-9e0a-2cab9342ecbf)

**Comment by niteshbalusu11** [comment]
Fixed in #1451
