### ISSUE TITLE
Do I have the control to choose regtest/testnet network ?

### ISSUE THREAD

**Issue by mohamedawnallah** [hsjoberg/blixt-wallet#1424]
## Description

I have the Blixt Android APK from the Play Store. Is it currently possible to choose the regtest or testnet network for testing purposes? I couldn't find these options in the settings.

**Comment by hsjoberg** [comment]
Hi, you can download the testnet APK here: https://github.com/hsjoberg/blixt-wallet/releases

We don't publish regtest APKs unfortunately. You will have to build Blixt yourself for that.

**Comment by mohamedawnallah** [comment]
Thanks a lot, @hsjoberg! Will. try this testnet apk!
