### ISSUE TITLE
Can't be used on Apple Intel Chips anymore

### ISSUE THREAD

**Issue by MyNameIsOka** [hsjoberg/blixt-wallet#1440]
I have been using Blixt Wallet on my Desktop MacMini with an Intel chip for some time.
When I wanted to open the app now it suddenly said that the app can't be used on Intel Chips.

Was there any announcement regarding this? 
This is a bit sudden and tbh quite annoying since I have to research how to get my funds out now.

**Comment by hsjoberg** [comment]
Thanks for the report. It should now be available again

**Comment by MyNameIsOka** [comment]
Thanks! Yes, it's working again.
