### ISSUE TITLE
I requested inbound capacity from lnbig service but how do I know the amount locked that can't be spent?

### ISSUE THREAD

**Issue by bitcoinuser** [hsjoberg/blixt-wallet#174]
Hi,

I requested inbound capacity from lnbig service but how do I know the amount locked that can't be spent?

I deposited 10 sats on Blixt but I was unable to spend it and no error message appear.

**Comment by hsjoberg** [comment]
Hi @bitcoinuser.

Under the Lightning Info section (the cloud icon on the Overview screen) you can see the capacity of your channels.

![image](https://user-images.githubusercontent.com/3824379/85079932-3ccf1000-b1c8-11ea-9383-f40d59eba0c2.png)

Did you see if the 10 bits you sent to Blixt went through?

Best
Hampus

**Comment by hsjoberg** [comment]
Latest version of Blixt now shows "Local reserve".
"Can reserve" has been updated to actually show what the user can receive.

![image](https://user-images.githubusercontent.com/3824379/85199711-fece0b00-b2f1-11ea-97ea-c1645ba8e43e.png)

**Comment by hsjoberg** [comment]
I'm closing this one now. I'll look into further improvements later on.
