### ISSUE TITLE
WebLN support/in-app browser

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#21]
Maybe start with Webview (https://github.com/react-native-community/react-native-webview) then move to GeckoView later on (a react-native component needs to be developed for this that could be its own npm-package).

BlueWallet has an in-app browser implementation here: https://github.com/BlueWallet/BlueWallet/blob/master/screen/lnd/browser.js

Store the domain where the purchase is from to be seen the transaction log.

Postpone if too complex.

**Comment by sesam** [comment]
Would using Webview also include using https://github.com/joule-labs/webln ?

**Comment by hsjoberg** [comment]
@sesam Yes and no.
As far as I can tell, this includes only the specification written in Typescript to follow when implementing webln.

I.e https://github.com/joule-labs/webln/blob/master/src/provider.ts

**Comment by hsjoberg** [comment]
Implemented in bc8f01ec3f1fc88ef38d47871271095301477055 though not public yet.

**Comment by hsjoberg** [comment]
Public in 353ca39 🔥️
