### ISSUE TITLE
Separate LndMobile.java to different native modules

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#225]
Maybe
* LndMobile.java
* LndMobileIpc.java (has the handler etc)
* LndMobileUitls.java

**Comment by sesam** [comment]
Related to #140 ?

**Comment by hsjoberg** [comment]
Correct! Thanks.
Both can actually be closed for now (already broke them up, to 2 parts now at least).
LndMobileTools.java maybe could be broken up even more, but I don't really see the need.
