### ISSUE TITLE
Tor lib does not compile anymore

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#254]

**Comment by hsjoberg** [comment]
The listing URL is reachable 
https://repo.spring.io/plugins-release/net/freehaven/tor/control/jtorctl/0.2/
But not the pod file:
https://repo.spring.io/plugins-release/net/freehaven/tor/control/jtorctl/0.2/jtorctl-0.2.pom

**Comment by hsjoberg** [comment]
According to this comment repo.spring.io is caching from Maven Central.
https://stackoverflow.com/a/22170251

Maven Central got the lib:
https://search.maven.org/artifact/info.guardianproject/jtorctl/0.4/jar

**Comment by nakinthorn** [comment]
i got this error 
`  > Could not find com.msopentech.thali:universal:0.0.3.
     Required by:
         project :app
   > Could not find com.msopentech.thali.toronionproxy.android:android:0.0.3.
     Required by:
         project :app`

it come from this issue right ?

**Comment by hsjoberg** [comment]
@nakinthorn Yes it sounds related.

You firstly need to initialize the Tor submodule by running the following:
`git submodule update --init`

Then to solve the issue at hand, the current solution is to add the the jcenter repository to get the tor module to compile properly in `tor/build.gradle`:

```diff
subprojects {
  repositories {
    mavenLocal()
    mavenCentral()
+   jcenter()
    maven { url "https://repo.spring.io/plugins-release" }
  }
}

```

After that, stand in the root folder and run `yarn build-tor-lib` (or `npm run build-tor-lib`) to compile the tor module. If that goes OK, run `yarn mainnet-debug` to get Blixt to compile.

Sorry for the mess here... I need to deal with this issue upstream at the [Tor Onion Library](https://github.com/thaliproject/Tor_Onion_Proxy_Library)

**Comment by nakinthorn** [comment]
> @nakinthorn Yes it sounds related.
> 
> You firstly need to initialize the Tor submodule by running the following:
> `git submodule update --init`
> 
> Then to solve the issue at hand, the current solution is to add the jcenter repository to get the tor module to compile properly in `tor/build.gradle`:
> 
> ```diff
> subprojects {
>   repositories {
>     mavenLocal()
>     mavenCentral()
> +   jcenter()
>     maven { url "https://repo.spring.io/plugins-release" }
>   }
> }
> ```
> 
> After that, stand in the root folder and run `yarn build-tor-lib` (or `npm run build-tor-lib`) to compile the tor module. If that goes OK, run `yarn mainnet-debug` to get Blixt to compile.
> 
> Sorry for the mess here... I need to deal with this issue upstream at the [Tor Onion Library](https://github.com/thaliproject/Tor_Onion_Proxy_Library)

after i run : yarn build-tor-lib
everything work fine until last command is : ./gradlew :android:publishToMaven
<img width="983" alt="Screen Shot 2563-12-06 at 23 51 20" src="https://user-images.githubusercontent.com/19216345/101286653-41db5680-381e-11eb-9742-6f12bbea63a5.png">
so an error will happen like this img

i think it is a root cause of `Could not find com.msopentech.thali.toronionproxy.android:android:0.0.3.`
when run yarn mainnet-debug

**Comment by hsjoberg** [comment]
@nakinthorn Hmm yes there seems to be some differences between macOS and Linux here (or possibly different Java versions). I've encountered this one as well.
In `/build-tor` change the last line to is publishToMavenLocal instead:

```diff
cd tor
./gradlew install
./gradlew :universal:build
./gradlew :android:build
-./gradlew :android:publishToMaven
+./gradlew :android:publishToMavenLocal
```

Let me know how it goes. :slightly_smiling_face:

**Comment by hsjoberg** [comment]
PR opened upstream https://github.com/thaliproject/Tor_Onion_Proxy_Library/pull/155
