### ISSUE TITLE
Show recovery info when restoring based on GetRecoveryInfo

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#267]
https://github.com/lightningnetwork/lnd/pull/4106

**Comment by sesam** [comment]
https://github.com/yyforyongyu/lnd/blob/987edc9d810f000d97bc9ac3ba1668e3bec77018/docs/recovery.md#starting-on-chain-recovery (and scroll down) shows the output. It's two books and one 0.0 up to 1.0 how far recovery has progressed.

How should the ⚡ ux be to show this?

**Comment by hsjoberg** [comment]
Implemented in f4105e04f569b9b4c328ade6a59c96a3ea5af83f.

@sesam Both `GetRecoveryInfo` returning the current state of recovery affairs as well as a button to start `tail -f`ing the lnd log was added to the SyncInfo modal.

|   |   |   |
|---|---|---|
| ![IMAGE 2021-11-18 01:23:10](https://user-images.githubusercontent.com/3824379/142308308-87f95a69-78a5-4f25-b077-9c685ad43530.jpg) | ![IMAGE 2021-11-18 01:23:35](https://user-images.githubusercontent.com/3824379/142308589-2709e6a3-24d1-4ce2-8273-cfbff34cbd93.jpg) | ![IMAGE 2021-11-18 01:23:43](https://user-images.githubusercontent.com/3824379/142308700-18984b59-6512-4f6f-9887-b6fe2461abbf.jpg)
