### ISSUE TITLE
LNURL-pay implementation naively appends ?amount regardless if querystring parameters already exists

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#271]
https://github.com/fiatjaf/lnurl-rfc/commit/50cf81c419a0c0e41e2dc28c46c282a02b88c1a2

**Comment by sesam** [comment]
Good first issue

**Comment by hsjoberg** [comment]
@sesam It would've been a good first issue if I didn't already fix it in 210b33ba8851fa0ee73ed74a6ec3b27510285dc8... :(

**Comment by hsjoberg** [comment]
Fixed in 210b33b
