### ISSUE TITLE
Add lightning-roulette.com to WebLN Browser

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#274]

**Comment by sesam** [comment]
To be added in same way as others already added? With icon? Good first issue?

**Comment by hsjoberg** [comment]
> To be added in same way as others already added? With icon? 

Yes. The way I did it with the others was getting a high res logo from the service/company in some way (website/reaching out on social etc) and then resize+convert it to webp. 

> Good first issue?

It would be if I had uploaded the needed scripts to accomplish this, I'll commit the needed tools soon.

**Comment by sesam** [comment]
I usually use online services, like crush.it, or pngquant when png is an option.

**Comment by hsjoberg** [comment]
I chose to with WebP here because it's going to be used in Blixt only anyway, and it's supported on both Android and iOS.

It's just using the official cwebp tool.

**Comment by hsjoberg** [comment]
Was added sometime ago.
