### ISSUE TITLE
Channel is stuck in pending state, seemingly never published to blockchain

### ISSUE THREAD

**Issue by torkelrogstad** [hsjoberg/blixt-wallet#278]
I've ended up in a really strange edge case around channel openings. I tried opening a channel, and it did not get published to the blockchain. Neither blockstream.info nor my `bitcoind` can find it. It appears in the list of pending channels on both Blixt and the remote LND (I control both). I tried force closing it, and that resulted in a new set of TXIDs I cannot find on-chain either.  

Since I'm now stuck with a pending channel that won't go away nor confirm, I can't open a new channel either, because there's a maximum of one channel open per peer... Any idea what's going on here?

Opening channel point: `b9940eca7a57ac425ba9dd7b0ea244f230c08375b158a1b04b43d6324df9db4d:0`
Force close remote LND TXID: `fee2809f7fa073351a8cb1e85ebe922e5ddf222b9a4911b9e5e0c7ece6fdcfd2`
Force close Blixt TXID: `97fd1169e30ec4517d91df94eeb55c48ef6e90794a37e717db5fb179acfe8a6c`

**Comment by torkelrogstad** [comment]
Checking back this morning, and I see that my channels are now open. Very strange that I couldn't see the opening TXs, though?

**Comment by hsjoberg** [comment]
@torkelrogstad thanks for raising this issue. Very strange...
Was this on mainnet or testnet?

That your own bitcoind-node couldn't find it makes me think the transaction(s) was invalid for some reason, or it having too low fee and ending up being pruned from the mempool. But this is just speculation, I suggest you check upstream with lnd.
Lnd log from Blixt is exportable via Settings -> Misc -> Copy log to local storage.

> because there's a maximum of one channel open per peer

Not for lnd, no.
But yes for pending channels, the maximum is 1.
It's configurable in lnd via the `maxpendingchannels` config, but Blixt is using the default value 1 right now (something that I plan to increase soon).

**Comment by torkelrogstad** [comment]
This was on testnet. Will peek through the logs when I have some free time

**Comment by hsjoberg** [comment]
@torkelrogstad Hmm I ran into the same issue as well actually. Perhaps something fishy is going on with lnd.

**Comment by hsjoberg** [comment]
Running `bitcoin-cli testmempoolaccept ...` showed that the transaction was indeed a valid transaction  and that it would be accepted under bitcoind with default configuration.

It seems like lnd just didn't broadcast the transaction.

**Comment by hsjoberg** [comment]
@torkelrogstad opening issue upstream https://github.com/lightningnetwork/lnd/issues/5130

**Comment by hsjoberg** [comment]
@torkelrogstad A fix for this is out for both Mainnet and Testnet versions of Blixt.
