### ISSUE TITLE
Cannot initialize Tor

### ISSUE THREAD

**Issue by nyonson** [hsjoberg/blixt-wallet#303]
I tried to initialize Tor immediately after installing the app on android. Now every time I start the app, it never gets past the "Initializing Tor" spinner screen. On the bottom of screen there is a big red bar with:

```
Attempt to invoke virtual method 'boolean java.io.File.setReadable(boolean)' on a null object reference
```

**Comment by hsjoberg** [comment]
@nyonson Thanks for raising this issue.

Hmm from what is remember and understand from this error message is that that the tor library failed to load somehow (`libtor.so`). The same error has appeared in the past, in perhaps other circumstances. 
I'm not sure how to reproduce this right now, but my thinking is that it's related to Android 11 (SDK 30).

**Comment by hsjoberg** [comment]
Okay, I'm able to reproduce this bug on my Samsung S20!
I'll conduct some testing and research.

**Comment by hsjoberg** [comment]
Okay! I'm able to reproduce this bug and I think I know what's wrong. I'll get back to you on this one.

**Comment by hsjoberg** [comment]
@nyonson Version 0.2.0 is out now on the Google Play Store, which should fix the Tor bug. Let me know if it works for you.

**Comment by nyonson** [comment]
Reporting back that with version 0.2.0 I was able to start the app and open a channel over tor. Thanks!

**Comment by hsjoberg** [comment]
Great!
