### ISSUE TITLE
Missing package names in ./android/app/google-services.json

### ISSUE THREAD

**Issue by emanuelb** [hsjoberg/blixt-wallet#314]
Compiling the latest commit to android apk with `cd android; ./gradlew assembleRelease` fail with errors:

Execution failed for task ':app:processChainregtestExperiment1ReleaseGoogleServices'.
> No matching client found for package name 'com.blixtwallet.regtest.experiment1'

Execution failed for task ':app:processChainregtestFakelndReleaseGoogleServices'.
> No matching client found for package name 'com.blixtwallet.regtest.fakelnd'

> No matching client found for package name 'com.blixtwallet.testnet.experiment1'

> No matching client found for package name 'com.blixtwallet.testnet.fakelnd'

So the package names need to be added to `./android/app/google-services.json` file, I overcome this issue by changing the values (which is incorrect fix, probably new entries need to be added to the json data):

`com.blixtwallet.testnet` to `com.blixtwallet.testnet.fakelnd`
`com.blixtwallet.fakelnd` to `com.blixtwallet.regtest.fakelnd`
`com.blixtwallet.testnet.debug` to `com.blixtwallet.testnet.experiment1`
`com.blixtwallet.regtest.experiment1.debug` to `com.blixtwallet.regtest.experiment1`
`com.blixtwallet.experiment1.debug` to  `com.blixtwallet.testnet`

**Comment by hsjoberg** [comment]
Thank you for the reporting this issue.

Yeah the `google-service.json` situation is a bit weird. I don't publish the actual file that contains the Google API credentials to the repository, but perhaps I should just do that to permanently fix this issue.

Right now as might have seen, I include a dummy `google-service.json`, but unfortunately it looks like I've missed some configurations.

**Comment by emanuelb** [comment]
> I don't publish the actual file that contains the Google API credentials to the repository, but perhaps I should just do that to permanently fix this issue.

if it's stuff that will be included in release apk anyway, aka running unzip or apktool on the apk file from google-play will show it, then it's no problem to include in the repo, but still worth to have dummy `google-service.json` file as default that enough to compile the app instead, as some server endpoints have limited/paid quotas, or to decrease "meaningless" results (not from release versions).

it can be achieved for example by having `deploy` branch that's only released versions are pushed into it + anything to reproduce release version, no need for such files with real API_KEYS for master/dev branches, which need to use dummy files (or files with values that points to user API KEYS... better to have in README how to generate them)

secret API_KEYS that are not part of the apk should not be pushed to any public branch.

**Comment by hsjoberg** [comment]
> if it's stuff that will be included in release apk anyway, aka running unzip or apktool on the apk file from google-play will show it, then it's no problem to include in the repo

Oh yeah, I'm fully aware of that this is easily extracted from the APK anyway.

> but still worth to have dummy google-service.json file as default that enough to compile the app instead, as some server endpoints have limited/paid quotas

I don't think it would be an issue, the google key is used for Google Drive backups, which is something you have to enable manually. Right now it automatically makes a backup every third day or for every new channel opening.

> or to decrease "meaningless" results (not from release versions).

In some cases it's not meaningless actually, the debug version of mainnet gets its own Google Drive file for backup. So it can be used to restore funds. (As you might know, there's a separate installable debug version alongside the production version for each chain.)

> it can be achieved for example by having deploy branch that's only released versions are pushed into it + anything to reproduce release version, no need for such files with real API_KEYS for master/dev branches, which need to use dummy files (or files with values that points to user API KEYS... better to have in README how to generate them)

Right now where with the current project state, I would like to keep it simple and use one single master branch.

I think I'll push the real `google-services.json` file to the master branch so this issue cannot appear again.

> secret API_KEYS that are not part of the apk should not be pushed to any public branch.

Oh yeah, of course. There are none fortunately.

**Comment by hsjoberg** [comment]
@emanuelb okay I've committed bcd561d, which includes the different `google-services.json` files which will are used for the production builds. I ran `./gradlew assembleRelease` and it worked for me.
