### ISSUE TITLE
Upgrade ndkVersion & remove duplicate ndkVersion config

### ISSUE THREAD

**Issue by emanuelb** [hsjoberg/blixt-wallet#316]
duplicate `ndkVersion` entries in `./android/app/build.gradle` file (not sure, but probably there need to be only 1 entry for ndkVersion, the static value)
https://github.com/hsjoberg/blixt-wallet/blob/d601c7b3d235479a1dfaf193696def50580564db/android/app/build.gradle#L126
https://github.com/hsjoberg/blixt-wallet/blob/d601c7b3d235479a1dfaf193696def50580564db/android/app/build.gradle#L129

Also the value in above file is `20.0.5594570` while in `./android/build.gradle` file it's `20.1.5948944`
https://github.com/hsjoberg/blixt-wallet/blob/d1bdbbdd1e80ec5b084d00a0dcbbce3c15c7405c/android/build.gradle#L9

latest stable version for ndk is: `22.1.7171670` , and latest LTS version is: `21.4.7075529` , see:
https://developer.android.com/ndk/downloads

upgrade the ndkVersion value after ensuring compilation & app works after the change.

**Comment by hsjoberg** [comment]
Thank you for reporting this issue. A mistake by me.

**Comment by hsjoberg** [comment]
Fixed in 67dc6a2.
