### ISSUE TITLE
Lnd log copy to clipboard not working

### ISSUE THREAD

**Issue by deafboy** [hsjoberg/blixt-wallet#336]
The clipboard stays empty after clicking the copy icon on "Lnd log" screen.

Blixit Wallet Testnet 0.2.3
Pixel 3 XL (GrapheneOS)

**Comment by hsjoberg** [comment]
@deafboy Thanks for the bug report!
This was addressed in f5b9128acfc7438eabe6c9492e9ae46d65be560f and is a part of the v0.2.4 release.
