### ISSUE TITLE
Set custom fee limits for payments

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#357]
> I think the default setting can use value like Phoenix wallet in fee settings, 15 sat as base fee and 0.3% for fee rate. I hope we can customize this setting as well in Blixt

**Comment by Darth-Coin** [comment]
In the pre-payment screen, can you add a button or a way that can "preview" the possible estimated fees that could be charged?

**Comment by hsjoberg** [comment]
Implemented in 665bcc902c3a74748f5047e5457e74bf77b1b06a.
Base fee stays hardcoded at 10 sats, but you can now set max LN fee %, which is the important part.
