### ISSUE TITLE
Text overlay on the services & contacts page

### ISSUE THREAD

**Issue by pavlenex** [hsjoberg/blixt-wallet#378]
While testing Blixt on iPhone 8 I noticed a minor visual overlap on the `Contacts` page.
This is quite a minor thing, but nevertheless reporting it 😄 

![Screenshot 2021-10-22 at 11 16 11](https://user-images.githubusercontent.com/36959754/138428556-6c97a56e-c10f-4708-a40c-646768db28f8.png)

**Comment by pavlenex** [comment]
Closing since I've verified this one has been fixed.

**Comment by hsjoberg** [comment]
> Closing since I've verified this one has been fixed.

@pavlenex Thank you for verifying.
