### ISSUE TITLE
No `back`button when restoring a wallet

### ISSUE THREAD

**Issue by pavlenex** [hsjoberg/blixt-wallet#382]
When user goes to `restore a wallet` on the initial setup, there's no way for them to go back to the previous screen in case they've made a mistake and want to `create a new wallet instead`.

Right now, user needs to quit an app in case they've ended up on this screen and want to go back.

![Screenshot 2021-10-22 at 11 43 03](https://user-images.githubusercontent.com/36959754/138432663-2ee39c66-d661-4d9c-9178-39bf1ad7d826.png)

**Comment by hsjoberg** [comment]
Thank you for opening this issue.

11abc5e8c93749611c443a1d8ab48a887a32f5cc As a quick fix I added a back icon for non-Android builds.

![Screenshot 2021-11-05 at 02 38 11](https://user-images.githubusercontent.com/3824379/140501413-cf1f8cfd-2979-4e7a-8382-196e41b8b75f.png)

Later on these screens should probably see some bigger revamp.

Also closes #343.
