### ISSUE TITLE
Android keyboard stores seed phrase

### ISSUE THREAD

**Issue by softsimon** [hsjoberg/blixt-wallet#410]
Upon restoring my wallet for the second time I noticed that the Android keyboard started to predict and fill in all my seed words in order. This is a security flaw.

**Expected behavior:**

The seed phrase box should not have the default keyboard auto complete enabled that stores what you type.

**Comment by Giszmo** [comment]
The default keyboard should not be used at all. Those might be any keyboard with features that even send all you write to some servers.

**Comment by hsjoberg** [comment]
Agree, I think creating Blixt Wallet's own software keyboard component in react-native with `View`s could work.

The text should be shown in a `Text` instead of a `TextView`.

**Comment by hsjoberg** [comment]
Addressed in bbee30e82082ae94e61782a9bdb8c1878ae73ef6.

In-app keyboard would be nice, maybe at a later time.
