### ISSUE TITLE
[UX/UI improvement] change location for saved logs

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#414]
### Actual behavior
When you click on save lnd logs it appear for few seconds a yellow message with the internal location where log file is saved:
/storage/emulated/0/android/data/com.blixtwallet/files/

many users don't know or can't find that location with a proper file explorer/ root explorer

### Expected behavior
Give the user the option to choose a handy location eg. downloads or documents or mSD card, something that can be accessed and encounter easily for moms. :)

NOTE: use same location for saving the LN backup channels

**Comment by hsjoberg** [comment]
Thank you for opening this issue @Darth-Coin.

I agree, I implemented this in ec8782469e4cbd9772fe564768ac8e833040f9af.

https://user-images.githubusercontent.com/3824379/147696216-aebef277-2b64-46ef-9d45-0587f6bc5c57.mp4

**Comment by hsjoberg** [comment]
Taking this in steps, should obviously be fixed for channel backup and general app log as well.

**Comment by Darth-Coin** [comment]
already done
