### ISSUE TITLE
[UI improvement] Add total size of channel

### ISSUE THREAD

**Issue by Darth-Coin** [hsjoberg/blixt-wallet#415]
Please, can you make the channel bar a bit longer and add on top the total size of the channel?
Easier for noobs to see what they have.
![image](https://user-images.githubusercontent.com/56997124/145728705-e7351912-15f0-461f-adf9-3b7e26af833d.png)

**Comment by hsjoberg** [comment]
Something like this should probably work.
(Ignore the actual numbers, fakelnd backend is funny.)

![IMAGE 2022-01-02 02:14:32](https://user-images.githubusercontent.com/3824379/147863603-0540e20a-b1fa-4078-8543-ac6799da2166.jpg)
work?

**Comment by hsjoberg** [comment]
Implemented in 36a297b

**Comment by Darth-Coin** [comment]
Yes, this is nice, clear, noobs can understand what is going on.
