### ISSUE TITLE
Sync screen shows Infinity%

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#427]
![IMAGE 2022-01-19 20:33:45](https://user-images.githubusercontent.com/3824379/150201187-8e844aee-294b-47eb-a81e-80004088bdbf.jpg)

**Comment by PatMulligan** [comment]
I'm experiencing this bug at the moment. I tried recovering a wallet with a channel back up from months ago that I thought I had lost the backup to. I can't be sure it's the right backup, but they seem to match up timewise. i.e., the date I backed up my seed phrase and the date I backed up the channels are only a few days apart. This dates back to August though, so hard to be sure.

If I can provide any logs that might help debug this issue lemme know!

**Comment by niteshbalusu11** [comment]
Fixed in #1451
