### ISSUE TITLE
Withdrawal request gives amount null (decimal ,)

### ISSUE THREAD

**Issue by Sroose** [hsjoberg/blixt-wallet#430]
When scanning a lnurl QR, the app has a popup called 'Withdrawal request'. The input field is configured to be a numerical field, so my IPhone shows only numbers and my local decimal separator which is a comma.

When entering the amount, eg 0,00001 BTC, the app creates an invoice with NULL as amount (lnbc1p3..). My assumption is because it does not recognize the decimal comma because amounts in integer bitcoin work.

This blocks the usage of this feature in many locales.

Not sure if related to https://github.com/hsjoberg/blixt-wallet/issues/323 but that one is closed.

**Comment by hsjoberg** [comment]
Hi @Sroose, thank you for the bug report.

It is related to #323, but I should've of course fixed it for LNURL-withdraw as well. 🤦‍♂️

**Comment by hsjoberg** [comment]
Fixed in 19d9c4b. Planning to have new release out soon that will include this fix.
