### ISSUE TITLE
Code is not a valid Bitcoin Lightning invoice

### ISSUE THREAD

**Issue by marospekarik** [hsjoberg/blixt-wallet#443]
Hi

I am trying to scan the following invoice:

`lntb24880n1p3rmgwrpp5cj2mlvl4sqakqhpa35rskrnl50te8z4wp3cdy03eae3kthl5t7usdt22fhkym6nv968xgpdypg82cnvd9eks6twvuszwnmjv3jhygp3xvmr5gzng4xycgzz23pjqen0wgsrzvps9cczq3242gnjqtfqf4skketjyp3x7mnyyqkjq4rgd9ejqurp09kk2mn5ypt5jnzvypr9y329tfzjqj2wypv5742jypt5znzvg42zcgrrdpjkx6eqdahzqargv5s8wetzwd5hgefqd9nzq6t5ypmkzueqwd6kxcm9wdekvatv9csyjapqwa5kcmpqv96hgmmdv96xjcmpd3k8jgrjv4682unwyp6kumr9wdejq7t0w5sxx6r9v96zqmmjyp3kzmnrv4kzqatwd9kxzar9wfskcmre9ccqzdaxqzuysp5pndfe84qwteq3d0fzspxzwq9jwwn0u6lw3vvj4ruwjtjkk7cjr8s9qyyssqluz8jphvlx2kwmkvztrklfal6svt8jysqsaxfldkhhax27ugn7h5ss8e06czn2tsq4yca23unqt0r8s4089r6vrnnmcw4nlt7u5z7ssq8kns4x`

However, I am getting: QR scan error: `Code is not a valid Bitcoin Lightning invoice`. I have tried to paste it manually with the same result.

**Comment by hsjoberg** [comment]
Hi @marospekarik.
This appears to be an invoice for Lightning on the Bitcoin Testnet network.

You can find Blixt Wallet Testnet for Android here: https://play.google.com/apps/testing/com.blixtwallet.
There's no Blixt Wallet Testnet version for iOS right now.

**Comment by marospekarik** [comment]
Oh, I didn't notice I am generating invoices on Testnet. Thanks for the clarification @hsjoberg !

**Comment by hsjoberg** [comment]
@marospekarik You're welcome!
