### ISSUE TITLE
Paid 0 amount invoice shows up as 0 sat in TransactionDetails

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/blixt-wallet#690]
Steps to reproduce (supposedly):

1. Pay a 0 amount invoice
2. Go to transaction details for the payment.

**Comment by niteshbalusu11** [comment]
I just tested this, I can't reproduce the issue and seems to be working fine. I think it can be closed.

**Comment by hsjoberg** [comment]
Fixed in 9fad204a0ce0665c6be6cc064dde1932b656eda3.
