### ISSUE TITLE
Add support for webln.keysend calls

### ISSUE THREAD

**Issue by bumi** [hsjoberg/blixt-wallet#765]
webln was extended by a `keysend` method: https://github.com/joule-labs/webln/pull/42

It would be great if the blixt lightning browser also supports this webln call. 
keysend is the main method used for podcasting 2.0 payments (see "[The "podcast:value" Specification](https://github.com/Podcastindex-org/podcast-namespace/blob/main/value/value.md)") and more related web applications are build.

Documentation:  https://www.webln.guide/building-lightning-apps/webln-reference/webln.keysend

**Comment by hsjoberg** [comment]
Hey @bumi!
I have already opened an issue about it here #445.

**Comment by bumi** [comment]
ohh, sorry. how did I miss that! thanks

**Comment by hsjoberg** [comment]
No worries
