### ISSUE TITLE
Channel opening stuck

### ISSUE THREAD

**Issue by Coinomatron** [hsjoberg/blixt-wallet#805]
Opened a channel to nicehash, tx confirmed, channel is inactive, log keeps printing: "unable to read init message: EOF"
Channel won't close either.

**Comment by Darth-Coin** [comment]
That usually appear when your Blixt can't connect to Blixt node to sync blocks.
Please try this https://blixtwallet.github.io/faq#no-sync and leave blank the info in "bitcoin node".

**Comment by Coinomatron** [comment]
Sorry for the late reply, was an issue with nicehash' node exactly at the time I was in the process of opening a channel. They had multiple channel closures as a result. I was able to contact them and have them force close from their side.
