### ISSUE TITLE
Blixt connecting to http instead of https on lnurl-pay

### ISSUE THREAD

**Issue by data-retriever** [hsjoberg/blixt-wallet#807]
Try sending something to ln@galtland.io

This is a https-only website and any http connection will receive a 308 Permanent Redirect from NGINX:
```bash
$ curl -v  http://ln.galtland.io/.well-known/lnurlp/ln
*   Trying 65.108.10.141:80...
* Connected to ln.galtland.io (65.108.10.141) port 80 (#0)
> GET /.well-known/lnurlp/ln HTTP/1.1
> Host: ln.galtland.io
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 308 Permanent Redirect
< Date: Tue, 09 Aug 2022 22:33:37 GMT
< Content-Type: text/html
< Content-Length: 164
< Connection: keep-alive
< Location: https://ln.galtland.io/.well-known/lnurlp/ln
< 
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Instead of using https directly (as defined by https://github.com/fiatjaf/lnurl-rfc/blob/legacy/lnurl-pay.md or https://github.com/fiatjaf/lnurl-rfc/blob/luds/01.md) Blixt will try to parse the html response and fail with `JSON Parse error: Unexpected token: <`

**Comment by hsjoberg** [comment]
Hi @data-retriever.
Blixt Wallet should always use HTTPS for Lightning Address, something else appears to be wrong here.
https://github.com/hsjoberg/blixt-wallet/blob/fa26ad9e9eb09218f04f46504ef8f29963f94c3e/src/state/LNURL.ts#L605-L606

ln@galtland.io should translate to https://galtland.io/.well-known/lnurlp/ln. But this URL leads to 404 (right now).

**Comment by data-retriever** [comment]
Now I see what was misconfigured on the server migration. Nervermind. Thank you!
