### ISSUE TITLE
Capture LN invoice when copied to clipboard

### ISSUE THREAD

**Issue by sesam** [hsjoberg/blixt-wallet#83]
After opening the wallet, keep watching the clipboard for a few minutes. Just checking every 20 seconds using a background service might work good enough for MVP level usage.

The goal UX is that copying a LN invoice to clipboard, the app somehow comes to life, maybe by showing a toast message that you can press to open a screen to view and confirm to pay the invoice. Generating a new invoice in-app should not trigger this, so you don't try to pay to yourself.

Impl ideas here: https://stackoverflow.com/questions/54728263/react-native-listener-for-change-in-clipboard

**Comment by hsjoberg** [comment]
I think the best approach for is this to show a prompt asking if the user wants to pay the invoice available in the clipboard.

On app start, the clipboard could just be checked without any issue.

For checking after the app has already been started, I think using react-native's [AppState](https://facebook.github.io/react-native/docs/appstate) makes most sense. It allows us to trigger an event should the app change its state (i.e from background to foreground (active)).

So the flow would be
1. User opens the app. The app registers an AppState listener
2. User puts the app in the background and goes to a page in a web browser
3. User copies an invoice from a web browser
4. User goes back to the app (puts it in the foreground)
5. An AppState event triggers, which allows us to check the clipboard and prompt the user

The app probably needs to have a temporary non-persistent database of all invoices that should not be prompted again.

We're already using AppState for working around an issue with fingerprint authentication here: https://github.com/hsjoberg/blixt-wallet/blob/f394df1d440a6c948fb2ab8630217b664bff3e72/src/windows/InitProcess/Authentication.tsx#L40

> The goal UX is that copying a LN invoice to clipboard, the app somehow comes to life, maybe by showing a toast message that you can press to open a screen to view and confirm to pay the invoice. Generating a new invoice in-app should not trigger this, so you don't try to pay to yourself.
>
> Impl ideas here: https://stackoverflow.com/questions/54728263/react-native-listener-for-change-in-clipboard

Thank you for looking this up.  
It might be too creepy to show a push notice. But it's something to look into in the future IMHO.

Perhaps it could be a setting the user chose to active, or at least give consent to.

**Comment by hsjoberg** [comment]
Implemented in 59db3133978779249eef6c0abc05cff22e4fe071
