### ISSUE TITLE
Support lightning: protocol for URLs

### ISSUE THREAD

**Issue by sesam** [hsjoberg/blixt-wallet#84]
When clicking a web link (that directly links, or redirects to) a URL beginning with lightning: it should open the wallet and show a suitable screen, enabling smooth payments.

Ideas for impl. https://hackernoon.com/react-native-deep-linking-for-ios-and-android-d33abfba7ef3

**Comment by hsjoberg** [comment]
Not sure if something has changed in Android 10 but deeplinks doesn't seem to work at all anymore on my OnePlus 6. I cannot get any of my 20+ apps to register `bitcoin:` URI's, let alone `lightning:`.

Moving outside of Q1 2020 milestone for now.

**Comment by hsjoberg** [comment]
NFC seems to still be possible as BLW supports it.

**Comment by hsjoberg** [comment]
BLW supports reading mime-type plain/text, but I cannot get it to work under react-native.

**Comment by hsjoberg** [comment]
https://facebook.github.io/react-native/docs/linking
https://reactnavigation.org/docs/en/deep-linking.html
https://developer.android.com/training/app-links/deep-linking#java

**Comment by hsjoberg** [comment]
Putting this one back to Q1 2020, It's actually fairly straight forward once you get a hang of it.

There are 3 different types of linking/sharing (maybe more).

* Website linking (via `<a>`-tag, triggered by registering support for `lightning:` protocol
* App share (via `Intent`) (an intent coming from another app, AFAICT uses mime-types)
* NFC scan. Can be triggered by both mime-type and protocol (`lightning:`), although there doesn't exist any mime-type for Lightning invoices right now (https://github.com/lightningnetwork/lightning-rfc/pull/404). "NDEF" support is coming with #98. Exactly how protocol based-tags work is still a mystery.

I'll support all three, although support for mime-type is bad as we don't have an assigned one yet, thus Blixt will support `text/plain` as BLW do (https://github.com/btcontract/lnwallet/blob/c105421d301998df34ac888f0f64dc8dc11dd631/app/src/main/AndroidManifest.xml#L65)

**Comment by hsjoberg** [comment]
Implemented in 0b7020796ff9cfacc80599425c01de5c4ed38aef
